### ISSUE TITLE
Pass-thru `mysql` arguments mechanism needs documentation

### ISSUE THREAD

**Issue by missjwo** [wp-cli/db-command#101]
On the [documentation page for DB command](https://developer.wordpress.org/cli/commands/db/query), there is an [example](https://developer.wordpress.org/cli/commands/db/query/#examples) which shows the `--skip-column-names` flag; yet no list of localised flags. Wondered if this was intentional and whether there were thoughts to add it in. 

It would be great to have a list of local parameters per command just like the [global parameter list](https://developer.wordpress.org/cli/commands/db/query/#global-parameters) that is currently available.

**Comment by schlessera** [comment]
The command preceding this example explains what the example actually shows:
```
# Pass extra arguments through to MySQL
```
So, the `--skip-column-names` flag is not actually something that WP-CLI provides, but a parameter that the `mysql` binary accepts. The example just shows that you can use such `mysql` arguments and they will be forwarded to the `mysql` binary.

The documentation from WP-CLI in this case would be this bit:
```
[--<field>=<value>]
Extra arguments to pass to mysql.
```

The arguments you can use are documented here:
https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html

**Comment by missjwo** [comment]
@schlessera  `Extra arguments to pass to mysql.` does not explain that the extra arguments are MYSQL native argments or that the arguements that can be used  as you said: 

> are documented here:
https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html

Adding that  extra tiny bit of information would be super helpful. It's not obvious to people who do not use WP CLI daily.

**Comment by schlessera** [comment]
@missjwo You are right, this could use better documentation.

I'll reopen and rename the issue.

**Comment by austinginder** [comment]
I suggest changing "Extra arguments to pass to mysql." to "Extra arguments to pass to [mysql command line options](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html).". Having the extra link I think will be helpful. Likewise should probably be updated for similar "Extra arguments to pass to mysqlcheck". If acceptable, I can submit a pull request.

**Comment by schlessera** [comment]
@missjwo With https://github.com/wp-cli/db-command/pull/117, @austinginder added links to the MySQL reference that details all the available switches. Do you think this is clear enough, or can you think of further improvements?

**Comment by schlessera** [comment]
@missjwo I'm closing this for now, assuming the documentation is sufficient. Feel free to let me know if you disagree.

**Comment by missjwo** [comment]
Ap[ologies for not getting back in a timely manner- the extra line from @austinginder  is spot on. Thanks for doing the PR!
