### ISSUE TITLE
wp db limit to db prefix

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/db-command#106]
Usually wp cli commands are limited in scope to the db prefix of the current installation, unless using e.g. --all-tables flag (e.g. in wp search-replace)

I suggest to also limit wp db reset (and perhaps also the other wp db commands) to the current page prefix (unless --all-tables is specified), as it will happen that people use wp db reset and, without realizing, delete ALL tables in the current database, instead of only the tables of the current installation.

**Comment by schlessera** [comment]
The `db reset` command actually drops the entire database, so we cannot restrict what tables it affects.

However, we now have a new `db clean` command that only drops the tables and can target only tables of the correct prefix: #93
