### ISSUE TITLE
size_format not working correct for DB size

### ISSUE THREAD

**Issue by Reiner030** [wp-cli/db-command#107]
Using latest version:
```
$ wp cli version
WP-CLI 1.5.1
```

The tables shows correct format as fixed in https://github.com/wp-cli/db-command/issues/64 :
```
$ wp db size --format=csv --size_format=mb --tables
Name,Size
wp_commentmeta,"1 MB"
wp_comments,"1 MB"
wp_links,"1 MB"
wp_options,"5 MB"
wp_postmeta,"2018 MB"
wp_posts,"45 MB"
wp_term_relationships,"4 MB"
wp_term_taxonomy,"1 MB"
wp_termmeta,"1 MB"
wp_terms,"1 MB"
wp_usermeta,"1 MB"
wp_users,"1 MB"
```

but database name is not written
```
$ wp db size --format=csv --size_format=mb
4511
```
; without option it works fine:
```
$ wp db size --format=csv
Name,Size
wordpress_test,"4730109952 B"

```

**Comment by schlessera** [comment]
Yes, I can confirm. The logic in here seems to be wonky: https://github.com/wp-cli/db-command/blob/v1.3.5/src/DB_Command.php#L867-L877

**Comment by schlessera** [comment]
@austinginder Yes, indeed, the problem is not related to the format, but rather the logic branching that is broken.

**Comment by austinginder** [comment]
Ah I see. In order to keep the numeric working as is, maybe a simply check for the format would be sufficient. That way any defined format will display correctly with a database label.
