### ISSUE TITLE
Automatically add the DB_PREFIX to the `columns` command.

### ISSUE THREAD

**Issue by dotancohen** [wp-cli/db-command#114]
Currently the `column` command requires the user to know the DB_PREFIX:
```
$ wp db columns posts
Error: Couldn't find any tables matching: posts

$ wp db columns wp_posts
Error: Couldn't find any tables matching: wp_posts

$ wp db columns foo_posts
+-----------------------+---------------------+------+-----+---------------------+----------------+
| Field                 | Type                | Null | Key | Default             | Extra          |
+-----------------------+---------------------+------+-----+---------------------+----------------
...
+
```

The command should accept the general `posts` parameter and add the proper DB_PREFIX.

**Comment by schlessera** [comment]
I think that might be a dangerous breaking change, leading to potentially unexpected results on multisite.

You can use the more explicit approach:
```
wp db columns $(wp db prefix)posts
```

**Comment by dotancohen** [comment]
Though I haven't run a multisite install so I'm not qualified to judge, how would that be different than how the `search-replace` command works on a specific database?

The more explicit approach mentioned is much too verbose to be useful, one would be better off just opening `db cli` and then `describe`ing the table of interest.

**Comment by swissspidy** [comment]
What if you want to run `wp db columns` against another table in the same database that has—for whatever reasons— a different prefix? It would be impossible if the prefix is automatically added.

**Comment by dotancohen** [comment]
How about a second command - i.e. `wp db describe foo` which would be the same as `wp db columns foo` but would add the DB_PREFIX to stock WP columns (posts, postmeta, etc)?

**Comment by danielbachhuber** [comment]
> The command should accept the general `posts` parameter and add the proper DB_PREFIX.

Given multiple WordPress installations can live within the same database, and a WordPress multisite installation can have multiple `posts` tables, I think magically adding the `$table_prefix` value will lead to unexpected results.

`wp db tables` can give you a list of the tables in a given WordPress installation:

```
$ wp db tables
wp_commentmeta
wp_comments
wp_links
wp_options
wp_postmeta
wp_posts
wp_term_relationships
wp_term_taxonomy
wp_termmeta
wp_terms
wp_usermeta
wp_users
```

We can solve other use cases with documentation.
