### ISSUE TITLE
WP DB won't work if db connection is secured

### ISSUE THREAD

**Issue by dotker** [wp-cli/db-command#126]
Hello guys and gals! Anyone got wp-cli to work with secured database connections? Seems not working and seems people are rarely using a secured database connections(for remote databases)?

**Comment by schlessera** [comment]
@dotker As you're referencing `mysqldump`, I assume you are trying to use the `wp db export` command.

The `MYSQLI_CLIENT_SSL` flag is specific to the PHP `mysqli` extension. The `mysqldump` binary is not PHP code, so the flag does nothing in this case.

Did you try adding the `--ssl` flag to the command? This would forward the `--ssl` flag to the `mysqldump` binary.

**Comment by mikebridge** [comment]
I think the `--ssl` flag is missing from `wp help db export`.   @schlessera 's suggestion works for me:

```bash
$ wp db export --path=/var/www/html
mysqldump: Got error: 9002: "SSL connection is required. Please specify SSL options and retry." when trying to connect
$ wp db export --ssl --path=/var/www/html
Success: Exported to 'wordpress-2020-09-15-ab86af3.sql'.
```
