### ISSUE TITLE
wp db export <[file]> always fails when used with --tables

### ISSUE THREAD

**Issue by craigpearson** [wp-cli/db-command#128]
This may be intentional, but it is not mentioned in documentation that a custom file cannot be passed as `<[file]>` whilst using the `--tables` option. In other commands such as search-replace for example `<[file]>` can be passed.

**Example**

```
wp db export /srv/www/example.com/shared/exports/partial-export.sql --tables=$(wp db tables --scope=blog --url=sub.example.com  --format=csv)
```

**Expected Result**
```
Success: Exported to '/srv/www/example.com/shared/exports/partial-export.sql'
```

**Actual Result**
```
Error: Too many positional arguments:--tables='wp_*_commentmeta,wp_*_comments,fat_*_links,fat_*_options,fat_*_postmeta,fat_*_posts,fat_*_term_relationships,fat_*_term_taxonomy,fat_*_termmeta,fat_*_terms'
```

_IDs obfuscated_

**Steps taken**

- Confirmed that $(wp db tables --scope=blog --url=sub.example.com --format=csv) returns CSV
- Manually provided tables to db export tables flag (to eliminate escape / quote issues)
- Escaped and quoted file names, directories etc
- Confirmed that the table option works as expected when <[file]> isn't provided

**Environment**

```
OS:	Linux 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.2
PHP version:	7.2.5-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.2/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/mnt/www/example.com/releases/20190117153517
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:	/mnt/www/example.com/releases/20190117153517/wp-cli.yml
WP-CLI version:	2.1.0
```

**Comment by schlessera** [comment]
@craigpearson I cannot replicate this, the command you provided works for me as-is (with my own domains in place, of course).

I can only assume that this is a problem with how your shell is set up.

My first hunch would be to verify the IFS setting of your shell.

Feel free to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/) if you want further assistance in diagnosing this issue.
