### ISSUE TITLE
Emoji like `🎥` will be changed to `?` after `wp db import`

### ISSUE THREAD

**Issue by miya0001** [wp-cli/db-command#144]
Some of emoji text will be garbed after `wp db import` and `wp db export`.

Following is an example to represent this issue.
https://github.com/wp-cli/db-command/compare/master...emoji-issue

The first test to check `🎥` will be passed but second one that is ran after `wp db import` will be failed.

Thanks. :)

Related: https://github.com/wp-cli/wp-cli/issues/3949

**Comment by miya0001** [comment]
Ah,  I found a solution to solve this problem as follows.

```
wp db export --default-character-set=utf8mb4
```

But I think this option should be passed as default.
Because it is difficult to realize emojis are broken for users.

What do you think?

**Comment by schlessera** [comment]
@miya0001 I'm open to adding this as a default setting, but I'm unsure what the exact ramifications are. Could this have any adverse effects that make it worse for some users? Could this break in some circumstances, for example where this character set might just not be available?

**Comment by sirtawast** [comment]
> @miya0001 I'm open to adding this as a default setting, but I'm unsure what the exact ramifications are. Could this have any adverse effects that make it worse for some users? Could this break in some circumstances, for example where this character set might just not be available?

What is the current default then?

**Comment by miya0001** [comment]
@sirtawast 

The default value of `--default-character-set` is `utf8`.
https://dev.mysql.com/doc/refman/5.5/en/mysqldump.html#option_mysqldump_default-character-set

**Comment by miya0001** [comment]
I couldn't found the solution to detect character set `utf8` or `utf8mb4`.

**Comment by wojsmol** [comment]
@miya0001 See [this](https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/) make/core blog post.

**Comment by morganhvidt** [comment]
I just lost all my emojis when migrating a site 🤪I'll try changing the `--default-character-set` next time. It would be nice if it's possible to have it as default.

**Comment by schlessera** [comment]
Yes, indeed, we should prioritize this to avoid situations like that. I'll work on getting this into the next release.

**Comment by dpacmittal** [comment]
Just got burned by this bug. We migrated the site to another server and noticed the emojis missing after a couple of hours. So we'll have to re-export (using mysqldump) and import the database and lose a few hours of user-generated content.

**Comment by schlessera** [comment]
Sorry to hear that, @dpacmittal . I got stuck on refactoring the DB command to make it easier to add defaults across the board (https://github.com/wp-cli/db-command/pull/160).

I'll try to get back to this as soon as possible to fix.

**Comment by mmirus** [comment]
Could be wrong, but is this already solved by specifying the correct `DB_CHARSET` in your WP config?

**Comment by MaximeCulea** [comment]
This  is not only a question of charset, but also of collate, in my case I had to:
- when doing exports between live and stagings sites, I had to precise the charset with wp cli export: 'wp db export --default-character-set=utf8mb4'
- on the staging website, I changed live from PHPMyAdmin the charset and collate on tables, to utf8mb4 and utf8mb4_unicode_ci. It worked directly so I did the same on live site.
- also, just to be sure, I also set proper charset and collate in wp-config
