### ISSUE TITLE
wp db check doesn't return error if core WP tables are missing

### ISSUE THREAD

**Issue by benlk** [wp-cli/db-command#148]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

### Describe the current, buggy behavior

With a database that only contains the posts table from wordpress:

```
$ wp db check
example.wp_posts                          OK
Success: Database checked.
```

This check returns a success, despite the database missing most of WordPress' core database tables.

#### Steps to reproduce

This database was created by `wp db import`ing a botched phpMyAdmin export, which contained only a single table rather than all tables.

You could also probably get similar behavior by selectively deleting tables from an install.

### Describe what you would expect as the correct outcome

I would expect an error to be output if any of the tables created by WordPress Core are missing.

### Let us know what environment you are running this on

```
$ wp cli info
OS:	Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
Shell:	/bin/bash
PHP binary:	/usr/local/Cellar/php/7.3.5/bin/php
PHP version:	7.3.5
php.ini used:	/usr/local/etc/php/7.3/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/user/sites/example
WP-CLI packages dir:	/Users/user/wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.3.0
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @benlk !

`wp db check` 'checks the current status of the database.' Generally, `wp db` commands are agnostic of the WordPress install.  You'll want to use `wp core is-installed` to verify WordPress' health.

**Comment by benlk** [comment]
@danielbachhuber I suppose that makes sense. 

Could we add documentation to the following locations to direct people to `wp core is-installed` as an additional check, after the db health check?

- https://developer.wordpress.org/cli/commands/db/check/
- https://developer.wordpress.org/cli/commands/db/
- the output of `wp db check` as a note after the "Success!" line?

**Comment by danielbachhuber** [comment]
@benlk Sure! Feel free to submit a pull request with your suggested text.
