### ISSUE TITLE
Register command execution points using named WP-CLI hooks

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/db-command#15]
WP-CLI runs most `wp db *` commands right after `wp-config.php` is located, but before the rest of WordPress is loaded: https://github.com/wp-cli/wp-cli/blob/d9d405a4ca01ba23e80277b8cb9000857e84e0cd/php/WP_CLI/Runner.php#L875

This is a special case system that should be switched to using named WP-CLI hooks.

From https://github.com/wp-cli/db-command/issues/1#issuecomment-299742567

**Comment by ScreamingDev** [comment]
Having a plugin for each project in our company, we want to extend some commands. `db import` is one of them. After this three other commands need to run. So it would be great if the import runs after plugins were loaded.

**Comment by danielbachhuber** [comment]
> So it would be great if the import runs after plugins were loaded.

We probably won't be changing the behavior of `wp db import`, so I'd encourage you to find a different approach.

**Comment by diggy** [comment]
Just a small note on `wp db` subcommands using `@WP_CLI::get_runner()->load_wordpress();` (note the error suppression with `@`): if there is a function definition present in wp-config.php these subcommands will fail, yielding no output at all. The error becomes clear when removing the `@`, e.g. `Fatal error: Cannot redeclare functionname()`

https://wordpress.slack.com/archives/C02RP4T41/p1503590888000029
