### ISSUE TITLE
Output only matching IDs in db search

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/db-command#158]
When using the `wp db search` command to search only in a given table (eg. `wp_posts`), I'd like the output to only contain IDs so I can export them elsewhere without having to extract them from the results which include the matching strings and the context.

Approximately the closest I can get to this is:

    wp db search foo wp_posts  --before_context=0 --after_context=0 --one_line

I'd like a flag for the opposite of `--matches_only`, probably `--ids-only`.

**Comment by danielbachhuber** [comment]
This seems reasonable.

**Comment by swissspidy** [comment]
We discussed this today during Hack Day. One suggestion to further enhance this is to leverage the formatter (`--format`) in a backward compatible manner. e.g. `--format=ids` or `--format=matches` (the default). The existing `--matches_only` arg could still be used, hence the backward compatibility.
`--format=ids` with multiple tables doesn't really make sense, so this could be prevented with a warning/error.

**Comment by i-am-chitti** [comment]
@johnbillion @swissspidy Is it still open for working? I can work on this.

**Comment by swissspidy** [comment]
I think so yes :) Feel free to look into it

**Comment by johnbillion** [comment]
@i-am-chitti There's a PR at #247. If you'd like to review that it would be helpful. I'm about to take a look myself.
