### ISSUE TITLE
Command for fetching the table prefix

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/db-command#18]
`wp db query <query>` is handy when you know the table prefix, or when it's set to the default `wp_`. If not, then there's no built-in way to write a portable version of something like `wp db query "SELECT * FROM wp_posts"` which uses the correct name for the posts table according to the table prefix.

It would be handy to have a command to fetch the database prefix:

    wp db query "SELECT * FROM $(wp db prefix)posts"

My current workaround is:

    wp db query "SELECT * FROM $(wp db tables *posts)"

While this does work, it seems fragile. Another option might be a command to fetch the complete table name:

    wp db query "SELECT * FROM $(wp db tablename posts)"

**Comment by danielbachhuber** [comment]
What about using the new `wp config get`?

**Comment by danielbachhuber** [comment]
Actually, I'd be amenable to adding `wp db prefix`, mostly for the shorthand convenience.

**Comment by johnbillion** [comment]
It seems like something that's more appropriate for the `db` command, even though core technically uses it in other places (eg for the capabilities options).
