### ISSUE TITLE
errorcode 255 for wp db export

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/db-command#196]
## Bug Report

Every export will create errorcode 255 - why?

```
wp --path="/html/wordpress" db export "/files/database-20210527.sql"
echo $?
255
```

**Comment by schlessera** [comment]
It looks like you are encountering a fatal error and the export fails. To know more about that, you need to enable PHP debug output. Try running the same command with `--debug`.

A successful export will show a `Success` message and exit with code `0`

**Comment by RoundAboutWEB** [comment]
I don't know why, but now message will be "0" and everything will be fine now - Thanks.
