### ISSUE TITLE
wp core install still use mysql_connect() from php5

### ISSUE THREAD

**Issue by wutzkachel** [wp-cli/db-command#202]
Hello,
First I created wp-config.php configuatione file with:
wp config create --path=public --dbname=kcowp --dbuser=root --dbpass=GanzGeheimesPasswortWasJederKennt --dbhost=KcoDb01

After that I try to create the wordpress database with the following commandline:
wp core install --url=www.mysite.de --title="MySite" --admin_user=admin --admin_password=admin --admin_email=info@info.de --path=public

and get the following error:
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/public/wp-includes/wp-db.php:1688
Stack trace:
#0 /var/www/html/public/wp-includes/wp-db.php(632): wpdb->db_connect()
It seems to be, that wp-cli still use php5 functions.

**Comment by wutzkachel** [comment]
I use the following version:
/var/www/html $ wp --version
WP-CLI 2.5.0

**Comment by ryotsun** [comment]
@wutzkachel 
I think you need to enable `mysqli` extension.

**Comment by wutzkachel** [comment]
Thank you very much for that hint!
That's it!
