### ISSUE TITLE
Problem `wp db export` in windows

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-cli/db-command#203]
Hi @schlessera, 
When I use `wp db export` in Cmd windows get Error:

![eere](https://user-images.githubusercontent.com/949491/126065207-08e2b61e-846e-482c-a9c7-f7c862ee4934.JPG)

There is a Double quote that Causes an error. When I run the `mysqldump` command separately, it is complete:

![345](https://user-images.githubusercontent.com/949491/126065246-3e79125a-d539-49f1-8b75-34f95cf33b51.JPG)

I saw this function in the source and I think its condition should be cleared:

![97649](https://user-images.githubusercontent.com/949491/126065302-4380266e-9b7e-4463-b5ed-1cef61b47647.JPG)

**Comment by monirulalom** [comment]
@mehrshaddarzi I am having same issue.  What is the filename of the source ?

**Comment by wojsmol** [comment]
@mehrshaddarzi @monirulalom For WP-CLI usage on Windows I recommend WSL or similar unix-like environment.

**Comment by lipemat** [comment]
I submitted pull request to resolve this issue:

1. https://github.com/wp-cli/db-command/pull/231
2. https://github.com/wp-cli/wp-cli/pull/5689

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/wp-cli/issues/5521

We can continue the conversation there
