### ISSUE TITLE
Emoji Icons not exported with wp db export

### ISSUE THREAD

**Issue by planetahuevo** [wp-cli/db-command#213]
## Bug Report
**Is your bug report directly related to a specific command?**
Yes wp db export
--- ✅ If you are in the correct location now... --->

- [X ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe the current, buggy behavior**

I was having a problem with an migration of a website that just after importing on the destination site, all widgets disappear. 

The content of the widget HTML (wp_options database, 'widget_custom_html') appears correctly imported on the database for a moment just before to disappear, the moment you load the page. 

On the database the content is replaced by 
`a:1:{s:12:"_multiwidget";i:1;}`

That destroyed all widgets on the site, of course.

I though that this was a problem with the import, the database, the theme, well, it has been a lot of testing to find the issue. 

The problem is that the export of the database using wp db replaces some emojis with ?? so the database "fails" somehow and remove the whole serialized content, eliminating all widgets on site. 

I think is because some icons 👨‍🏫 are replaced by ?? instead, so that breaks the whole thing. 

To replicate: 
Create a widget Custom HTML, using classic widgets (I have not tested it with gutenberg widgets). 
Original content: 

`ecommerce</i> 👨‍🏫`

Exported content (and imported):
` ecommerce</i> ?? `

Exporting with mysqldump exports correctly the 🚀 and the import with wp db works fine. 

**Describe what you would expect as the correct outcome**

I expect the export file to have the emojis 🚀 and not ? instead.

```
OS:     Linux 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.7
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 8.0.19-10 for debian-linux-gnu on x86_64 (Percona Server (GPL), Release '10', Revision 'f446c04')
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/EDITED/htdocs
WP-CLI packages dir:    /home/EDITED/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0
```

**Provide a possible solution**
No idea.

**Comment by wojsmol** [comment]
This should be fixed by https://github.com/wp-cli/db-command/pull/199 so in WP-CLI 2.5.0. Please check charset in wp-config.php file on affected website.

**Comment by planetahuevo** [comment]
`define( 'DB_CHARSET', 'utf8' );`

**Comment by wojsmol** [comment]
`define( 'DB_CHARSET', 'utf8' );`
This is the main issue.

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make [WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by planetahuevo** [comment]
Yeah, yeah. I got it. I thought it was a problem with the db export, but clearly is not.

**Comment by wojsmol** [comment]
This was a issue for `db-command` before `2.0.14` so before WP-CLI 2.5.0 if you are using phar.

**Comment by planetahuevo** [comment]
I think it is still an issue (not a bug) as WP recommends the default as utf8
https://wordpress.org/support/article/editing-wp-config-php/#database-character-set
But I can understand also why you do not consider this a bug. I will use the '--default-character-set' or mysqldump that also works fine.

I have contacted my hosting as they are setting up the wp-config as per the recommended by wordpress.org website, but in this case, it is not the best idea. 

Thanks

**Comment by wojsmol** [comment]
cc @schlessera Please check if there is anything  to change on WP-CLI side of things.
