### ISSUE TITLE
Document that `wp db optimize` runs on the entire database

### ISSUE THREAD

**Issue by ailaG** [wp-cli/db-command#24]
I have 2 separate installations of Wordpress (Multisite) in 2 different folders. wp-cli commands run differently under each folder.
Yet wp db optimize optimizes tables for both installations.

Not that I mind, but someone else may.

**Comment by danielbachhuber** [comment]
> Yet wp db optimize optimizes tables for both installations.

This is correct. `wp db optimize` optimizes the entire database.

**Comment by ailaG** [comment]
Unlike other wp-cli commands... So that behavior is kind of unexpected.

**Comment by danielbachhuber** [comment]
> So that behavior is kind of unexpected.

We can add further documentation that `wp db optimize` runs on the entire database.

**Comment by rahul286** [comment]
@ailaG you may use 

```
mysqlcheck `wp config get | grep DB_NAME | awk {'print $2'}` `wp db tables | tr '\n' ' '`
```

@danielbachhuber `wp db tables` returns only tables for WordPress install. So would it be better `wp db optimize` works on tables returned by `wp db tables`?

**Comment by danielbachhuber** [comment]
> So would it be better `wp db optimize` works on tables returned by `wp db tables`?

Changing the behavior at this time would be a breaking change, so I think documenting the existing behavior is a more appropriate fix.

**Comment by rahul286** [comment]
@danielbachhuber fine. Updated doc.
