### ISSUE TITLE
regex search vs. UTF-8 encoding

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/db-command#250]
## Bug Report

- [ ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

```
wp db search '\p{Cf}' --regex
```

Regexp search for character classes finds individual bytes of an UTF-8 encoded character.
e.g. í in "hírlevél"
the result is displayed like "blog h▒▒rlevél feliratkozás"

How to search in UTF-8 encoded text?

BTW `wp db search "$(printf '\xc3')" --regex` also finds the first byte of í (actually all characters encoded on two bytes)

**Comment by szepeviktor** [comment]
Same goes for `search-replace` command.

**Comment by danielbachhuber** [comment]
> How to search in UTF-8 encoded text?

@szepeviktor I'm not sure I follow. Can you share an example of what you tried, what you saw, and what you expected to see?

**Comment by szepeviktor** [comment]
> Can you share an example of what you tried, what you saw, and what you expected to see?

Issued this command: `wp db search "$(printf '\xc3')" --regex`
Seen result like: `blog h▒▒rlevél feliratkozás`
half of the "block" character was highlighted, so the UTF-8 two byte character was split into two.

**Comment by szepeviktor** [comment]
`\p{Cf}` regular expression is for finding "Format characters", I am looking for U+200B ZERO WIDTH SPACE in post content and in post meta.

**Comment by szepeviktor** [comment]
### Solution

You need to add `--regex-flags=u` to be UTF-8 compatible 😃 
https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php

**Comment by danielbachhuber** [comment]
@szepeviktor Glad I was here to help you figure it out! 😁
