### ISSUE TITLE
Introduce `wp db export --stdout`

### ISSUE THREAD

**Issue by miya0001** [wp-cli/db-command#35]
My use case is following.

```
$ wp @stag db export --stdout | wp @prod db import -
```

It looks very useful.
I want to try it.

**Comment by danielbachhuber** [comment]
👍

**Comment by gitlost** [comment]
Via https://github.com/wp-cli/db-command/pull/37

**Comment by schlessera** [comment]
I not really happy with this change.

`wp db export` already had this functionality, and you could do the above with this command:

```
$ wp @stag db export - | wp @prod db import -
```

There's not really a reason to add a second mechanism for `STDOUT` now, and I don't think it is a good idea to have multiple ways for a command to achieve a given task.

I would like to further discuss this before the next release.

**Comment by miya0001** [comment]
@schlessera 

Actually, I didn't realize that we can pass the `-` before I read the code.
I am not sure which should we choice, but I don't have any objections to revert this change.

Let's open new issue. :)

**Comment by miya0001** [comment]
I opened a new issue https://github.com/wp-cli/db-command/issues/38.
