### ISSUE TITLE
Do we need the argument `--stdout` for `wp db export`?

### ISSUE THREAD

**Issue by miya0001** [wp-cli/db-command#38]
We introduced the `--stdout` at the `wp db export` at #37 .
But we need more discuss before next release.

Reated:
* #35
* #37 
* https://github.com/wp-cli/export-command/pull/13

**Comment by danielbachhuber** [comment]
I'm amenable to reverting. Let's keep the test and example you added though.

**Comment by miya0001** [comment]
@schlessera 😄
