### ISSUE TITLE
Add example of how to search and delete results

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/db-command#51]
For those wanting to clean up parts of their database, it'd be neat to have a `wp db search` example indicating how to search for a string and delete the resulting database entry.

> danhgilmore [7:14 AM] I think I've asked this in the past, but I'm just now getting back to working with wp-cli....is there a way to search/delete instead of search/replace?
> [7:15] I am cleaning up our DB, and there's a lot of things orphaned in the wp_X_options tables that I'd like to search for and then remove.
> janw.oostendorp [7:37 AM] pass an empty string within quotes? Won't delete empty meta/options
> danhgilmore [7:38 AM] Yeah, I'm trying to remove the records from the database :confused:

From https://wordpress.slack.com/archives/C02RP4T41/p1506435293000491

**Comment by marksabbath** [comment]
Hey @danielbachhuber I couldn't find a properly command/method to perform this kind of action, however, while reading the code of `wp db seach`, I figured that we could add a new arg to `wp db search`, something like `--delete-records`, which would properly fit in these cases.

What are your thoughts about this idea? If you do think that this would be a good idea, I could volunteer to implement that.

**Comment by schlessera** [comment]
@marksabbath I think that would make more sense as a separate command, as deleting rows is not a variation of "searching", but rather a completely different operation.

Also, it would need safety features like `--dry-run` or `--interactive`.

Do you care to add this as a new issue to [`wp-cli/ideas`](https://github.com/wp-cli/ideas/issues) to discuss in more detail?

**Comment by marksabbath** [comment]
You bet @schlessera gonna add that there right away.

**Comment by missjwo** [comment]
Not sure if this is helpful, but I recently just had to do  ```wp user delete $(wp db query 'SELECT ID FROM wp_users WHERE user_email NOT LIKE \"%@domain.example\"' --skip-column-names) --network --yes'``` for a project

**Comment by danielbachhuber** [comment]
Addressed in #122
