### ISSUE TITLE
Large requests exhaust max_connections

### ISSUE THREAD

**Issue by jgonyea** [wp-cli/db-command#62]
Performing large requests vi `wp db` creates situations where the MySQL max_connections is exhausted.  We have a shared DB server (MySQL 5.0.95-log) on CentOS 5.10.

Running `wp db reset` from a Wordpress app server takes a very long time (large multisite database), and requests pile up, eventually causing the MySQL max_connections limit (currently 160) to be reached.

Performing a drop table query directly on the sql server does not exhaust the connections.

Am I missing something regarding the usage of `wp db` commands and remote SQL servers?

**Comment by gitlost** [comment]
A guess is it might have something to do with or at least be aggravated by `wp db` shelling out to mysql instead of using `$wpdb`.

**Comment by gitlost** [comment]
I just tried changing `DB_Command::run_query()` (used by `db reset`, `db create` and `db drop`) to:
```
private static function run_query( $query ) {
	global $wpdb;
	if ( $wpdb ) {
		if ( false === $wpdb->query( $query ) ) {
			WP_CLI::halt( 1 );
		}
	} else {
		self::run( '/usr/bin/env mysql --no-defaults --no-auto-rehash', array( 'execute' => $query ) );
	}
}
```
and the tests passed ok (though I notice we've no test for `db drop`). It's probably something worth doing even if it doesn't solve this problem...

**Comment by gitlost** [comment]
Just tried using `mysqli_query()` etc directly - works and a bit faster:
```
private static function do_sql( $query ) {
	static $dbh = null;

	if ( null === $dbh ) {
		$dbh = mysqli_init();

		$host    = DB_HOST;
		$port    = null;
		$socket  = null;
		$is_ipv6 = false;

		if ( $host_data = self::parse_db_host( $host ) ) {
			list( $host, $port, $socket, $is_ipv6 ) = $host_data;
		}

		$client_flags = defined( 'MYSQL_CLIENT_FLAGS' ) ? MYSQL_CLIENT_FLAGS : 0;

		if ( ! mysqli_real_connect( $dbh, DB_HOST, DB_USER, DB_PASSWORD, null, $port, $socket, $client_flags ) ) {
			$dbh = false;
			return null;
		}
	}
	if ( ! $dbh ) {
		return null;
	}
	return mysqli_query( $dbh, $query );
}
```
where `parse_db_host()` is a direct copy of that in `wpdb`. Not as attractive but still might be worth doing...

**Comment by danielbachhuber** [comment]
> Running `wp db reset` from a Wordpress app server takes a very long time (large multisite database), and requests pile up, eventually causing the MySQL max_connections limit (currently 160) to be reached.
> 
> Performing a drop table query directly on the sql server does not exhaust the connections.

Forgive me if I'm being dense, but aren't these two different operations? The former calls `DROP DATABASE IF EXISTS` to drop the entire database, but the second only drops a single table.
