### ISSUE TITLE
Default value of size_format flag is incorrect

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/db-command#64]
The help doc for `wp db size` states that the default value of the `--size_format` flag is `b` (for bytes), but that's not the case. The default size format appears to be the largest unit that fits the value.

**Comment by marksabbath** [comment]
According to the [size_format](https://codex.wordpress.org/Function_Reference/size_format) documentation, you're correct @johnbillion, it will indeed "_Convert a given number of bytes into a human readable format, using the largest unit the bytes will fit into._".

My suggestion would be removing the `default` on help, which would make it look like:

```
  [--size_format]
    Display the database size only, as a bare number.
    ---
    options:
     - b (bytes)
     - kb (kilobytes)
     - mb (megabytes)
     ---
```

Does it sound reasonable for you @danielbachhuber @schlessera ? If yes, I would be happy to make this update.

**Comment by danielbachhuber** [comment]
Sure, thanks @marksabbath.

When playing around with this, I noticed that `--size_format` has ambiguous behavior when `--tables` is included:

```
$ wp db size --tables --size_format=mb
+-----------------------+-------+
| Name                  | Size  |
+-----------------------+-------+
| wp_users              | 64 KB |
| wp_usermeta           | 48 KB |
```

Want to fix that too?

**Comment by danielbachhuber** [comment]
🔨
