### ISSUE TITLE
Introduce `wp db ack`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/db-command#7]
Find a specific string in the database, a la https://github.com/runcommand/db-ack

**Comment by gitlost** [comment]
Is there anything other than basically a straight merge required here? As mentioned in https://github.com/wp-cli/search-replace-command/issues/1#issuecomment-318697810 I'd like to do this.

**Comment by danielbachhuber** [comment]
> Is there anything other than basically a straight merge required here?

Probably add a few more tests and clean the code up a bit. I had also wanted to add https://github.com/runcommand/db-ack/issues/5

**Comment by gitlost** [comment]
Do you want to do this instead?

Re https://github.com/runcommand/db-ack/issues/5 I think just merging anyway and iterating on that would be good.

**Comment by danielbachhuber** [comment]
> Do you want to do this instead?

It's not high on my list of things to do. If you want to pick it up, feel free to go for it.

**Comment by miya0001** [comment]
It is a personal question, what does `ack` mean?

**Comment by miya0001** [comment]
Ah, I see http://beyondgrep.com/.
I saw dictionary... 😓
