### ISSUE TITLE
`wp db tables` does not obey prefix when using table wildcards

### ISSUE THREAD

**Issue by schlessera** [wp-cli/db-command#73]
Default behaviour of `wp db tables` is to only show tables that match the prefix that is set in the `wp-config.php` file.

However, if a wildcard is added to only retrieve a specific subset of tables, the prefix in `wp-config.php` is ignored, and all matching tables are shown.

<img width="762" alt="image 2017-12-21 at 11 44 50 am" src="https://user-images.githubusercontent.com/83631/34252541-60667f6e-e644-11e7-8cff-87c3ea463f58.png">

In the above screenshot, the queries with a wildcard not only show `as_wp_posts`, but also `wp_posts`. The expected behavior would be to only show `as_wp_posts`. Even trying to force the (default) option to obey the prefix does not produce the expected result.

**Comment by BhargavBhandari90** [comment]
@schlessera checking with master branch

![db-table](https://user-images.githubusercontent.com/19459637/34684253-8429afd6-f4ca-11e7-97ab-774e9aa496a6.png)

**Comment by gitlost** [comment]
@BhargavBhandari90  do
```
wp db query "CREATE TABLE xx_wp_posts ( id int )" --path=/var/www/wp.me/htdocs
```
and then try...

**Comment by BhargavBhandari90** [comment]
Thanks @gitlost. @schlessera Made some changes in `wp-cli/wp-cli` for this.
