### ISSUE TITLE
Provide parameters for DB user/password

### ISSUE THREAD

**Issue by lucrus73** [wp-cli/db-command#74]
There's the need for parameters to specify database username and password other than the ones in `wp-config.php`.

The [`--<field>=<value>` syntax](https://developer.wordpress.org/cli/commands/db/export/) works for the password, but it fails for the user because the [`--user`](https://make.wordpress.org/cli/handbook/config/#global-parameters) parameter is already taken to specify the WordPress user.

See [here](https://github.com/wp-cli/ideas/issues/76) for more details.

I suggest to create new parameters, namely `--dbuser` and `--dbpass` and bind them to the `--user` and `--password` parameters of `mysqldump` respectively (albeit a new mapping for `--password` is not strictly required, but adding it nonetheless makes things cleaner).

**Comment by schlessera** [comment]
I consider this a bug, as we're unintentionally hiding the login mechanism behind similarly named, but completely unrelated global parameters.

**Comment by gitlost** [comment]
Agree, the suggested solution sounds good.

**Comment by szepeviktor** [comment]
Please consider also `--dbhost`

**Comment by lucrus73** [comment]
> Please consider also --dbhost

What would be the use case for `--dbhost`? And why not `--dbname` too, then? Have you tried passing `--host` through the  [`--<field>=<value>` syntax](https://developer.wordpress.org/cli/commands/db/export/)?

I had the need to connect to the same database specified in `wp-config.php`, but with a different user to gain more privileges, hence `--dbuser` and `--dbpass` make sense.

Anyway, if you think --dbhost is needed, you should probably file a different bug report.

**Comment by schlessera** [comment]
@szepeviktor The `--host` argument is not hidden by a global parameter, so there's no need for a workaround in that case.

**Comment by szepeviktor** [comment]
OK,. Thank you.
