### ISSUE TITLE
wp db size does not support gb or tb as options

### ISSUE THREAD

**Issue by lukecav** [wp-cli/db-command#80]
https://developer.wordpress.org/cli/commands/db/size/#options

Currently the options are
options:
– b (bytes)
– kb (kilobytes)
– mb (megabytes)

https://github.com/wp-cli/db-command/blob/master/src/DB_Command.php#L716

Confirms that neither **gb (gigabyte)** or **tb (terabyte)** are supported as options.

**Comment by schlessera** [comment]
Fixed via #81

**Comment by lukecav** [comment]
Seems that the doc needs to be updated to reflect the additional options. 
https://developer.wordpress.org/cli/commands/db/size/
