### ISSUE TITLE
Suggestion for size command to make the default size_format KB or MB

### ISSUE THREAD

**Issue by wpbullet** [wp-cli/db-command#86]
I'm loving this new `db size` command and I always find myself adding the `--size_format` flag because bytes are not very human-readable friendly. I'd like to suggest making the default `size_format` KB or MB, personally I think megabytes make more sense. Here is the output from the three commands for a default WordPress installation.

` wp db size --tables`

```
+-----------------------+---------+
| Name                  | Size    |
+-----------------------+---------+
| wp_commentmeta        | 49152 B |
| wp_comments           | 98304 B |
| wp_links              | 32768 B |
| wp_options            | 65536 B |
| wp_postmeta           | 49152 B |
| wp_posts              | 81920 B |
| wp_term_relationships | 32768 B |
| wp_term_taxonomy      | 49152 B |
| wp_termmeta           | 49152 B |
| wp_terms              | 49152 B |
| wp_usermeta           | 49152 B |
| wp_users              | 65536 B |
+-----------------------+---------+
```

`wp db size --tables --size_format=mb`

```
+-----------------------+------+
| Name                  | Size |
+-----------------------+------+
| wp_commentmeta        | 1 MB |
| wp_comments           | 1 MB |
| wp_links              | 1 MB |
| wp_options            | 1 MB |
| wp_postmeta           | 1 MB |
| wp_posts              | 1 MB |
| wp_term_relationships | 1 MB |
| wp_term_taxonomy      | 1 MB |
| wp_termmeta           | 1 MB |
| wp_terms              | 1 MB |
| wp_usermeta           | 1 MB |
| wp_users              | 1 MB |
+-----------------------+------+
```

`wp db size --tables --size_format=kb`

```
+-----------------------+-------+
| Name                  | Size  |
+-----------------------+-------+
| wp_commentmeta        | 48 KB |
| wp_comments           | 96 KB |
| wp_links              | 32 KB |
| wp_options            | 64 KB |
| wp_postmeta           | 48 KB |
| wp_posts              | 80 KB |
| wp_term_relationships | 32 KB |
| wp_term_taxonomy      | 48 KB |
| wp_termmeta           | 48 KB |
| wp_terms              | 48 KB |
| wp_usermeta           | 48 KB |
| wp_users              | 64 KB |
+-----------------------+-------+
```

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @wpbullet. I've thought the same, bytes aren't very helpful, so I'd be open to the change. We'd need to decide whether it should be considered a breaking change (and associated ramifications).

**Comment by wpbullet** [comment]
My pleasure @danielbachhuber and thank you for all you do! I'd be happy to help test the breaking-ness level of the change and any ramifications.

**Comment by schlessera** [comment]
@wpbullet The default is just the lowest value, and that matches what other shell tools provide by default.

If you find bytes useless, you can already choose a different default through your `~/.wp-cli/config.yml` file. Just add the following to that file, and it will change the default size format default for your user:
```
db size:
  size_format: kb
```
This allows you to choose whatever default you find most useful, without breaking backwards compatibility.
