### ISSUE TITLE
Options to be able to exclude post revisions and replace GUIDs

### ISSUE THREAD

**Issue by lukecav** [wp-cli/db-command#88]
Options should exist to exclude post revisions when running **wp db export** as well as replacing GUIDs when the db export is run.

Also an option to exclude spam comments when running **wp db export** would be very useful.

**Comment by danielbachhuber** [comment]
Hi @lukecav,

Thanks for the suggestion. Given the uniqueness of this request, I think this would be better implemented as one or more standalone community commands. Hypothetically, there's the potential need to exclude every part of the database.
