### ISSUE TITLE
Request adding `--where` to `wp db export`

### ISSUE THREAD

**Issue by austinginder** [wp-cli/db-command#89]
I see `wp db export` uses mysqldump. I'd like to be able to pass a `--where` argument to the [mysqldump's where option](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_where). The would allow for a selective data dumps. Examples of how I think it should work.

**Export selective posts**
wp db export --tables=wp_posts --where="ID in (100,101,102)" --no-create-info

**Export relating meta for selective posts**
wp db export --tables=wp_postmeta --where="post_id in (100,101,102)" --no-create-info

For reference the following mysqldump does work.

mysqldump -u$(wp config get DB_USER) -p$(wp config get DB_PASSWORD) $(wp config get DB_NAME) --no-create-info --tables wp_posts --where="ID in (100,101,102)"
mysqldump -u$(wp config get DB_USER) -p$(wp config get DB_PASSWORD) $(wp config get DB_NAME) --no-create-info --tables wp_postmeta --where="post_id in (100,101,102)"

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @austinginder.

> I'd like to be able to pass a `--where` argument to the mysqldump's where option. 

Did you try this by chance? It worked in my testing; `wp db export` passes through any additional arguments to `mysqldump`. See https://developer.wordpress.org/cli/commands/db/export/#options

**Comment by austinginder** [comment]
So I thought I had and wasn't having success but I just tried and it does work! I suggest an example be added to the docs as I'm sure others would like to know how it's done. 

I am having issues using `--no-create-info` which returns the error `mysqldump: unknown variable 'create-info='`. Seems like something is taking off the "no" part. This flag is needed whenever doing a data only dump. Any ideas if that's a bug?

**Comment by austinginder** [comment]
After some more trial and error, it seems to work setting if set to true `--no-create-info=true`.  Is that documented or a bug? So the following revised works as intended!

**Export selective posts**
wp db export --tables=wp_posts --where="ID in (100,101,102)" --no-create-info=true

**Export relating meta for selective posts**
wp db export --tables=wp_postmeta --where="post_id in (100,101,102)" --no-create-info=true

**Comment by danielbachhuber** [comment]
> I am having issues using `--no-create-info` which returns the error `mysqldump: unknown variable 'create-info='`. Seems like something is taking off the "no" part.

This is a WP-CLI "feature" where `--no-` negates the argument.

> I suggest an example be added to the docs as I'm sure others would like to know how it's done.

Cool — up for submitting such a PR?

**Comment by austinginder** [comment]
I'll give it a go. Apologies ahead of time as this will be my first PR. Learning as I go.
