### ISSUE TITLE
Add new db clean feature to only drop the tables of the WordPress instance

### ISSUE THREAD

**Issue by lucrus73** [wp-cli/db-command#92]
We need a feature to drop only the tables of a WordPress instance. 
The currently existing `wp db reset` feature drops the entire database, which is not the same, as explained [here](https://github.com/wp-cli/db-command/issues/87#issuecomment-374004365).

The proposed name is `wp db clean`.

**Comment by marksabbath** [comment]
Working on it.

**Comment by schlessera** [comment]
Fixed via https://github.com/wp-cli/db-command/pull/93
