### ISSUE TITLE
wp db export fails on Percona-XtraDB-Cluster – mysqldump with --no-defaults

### ISSUE THREAD

**Issue by d--j** [wp-cli/db-command#95]
On [Percona XtraDB Cluster](https://www.percona.com/software/mysql-database/percona-xtradb-cluster) with `pxc_strict_mode = ENFORCING` (the default) 
`wp db export -` fails with the following error message:

```shell
mysqldump: Got error: 1105: "Percona-XtraDB-Cluster prohibits use of LOCK TABLE/FLUSH TABLE <table> WITH READ LOCK with pxc_strict_mode = ENFORCING" when using LOCK TABLES
```
For this Server/Server configuration `mysqldump` needs to be executed with an additional argument `--lock-for-backup`. Since `wp db export` calls `mysqldump` with the `--no-defaults` setting I cannot add this in a configuration file but need to provide it as a command line argument.

I think it would make sense to add the ability to append arbitrary command line arguments to the `mysqldump` call. This would be beneficial not only for this case but also for e.g. adding `--no-lock-tables` or `--single-transaction` to the `mysqldump` call and thus tweak the desired consistency and concurrency of the database backup.

**Comment by d--j** [comment]
Oh sorry,  I did not realised that adding arbitrary arguments to `wp db export` -- e.g. `wp db export - --lock-for-backup` already does what I need.

**Comment by danielbachhuber** [comment]
@d--j Any open questions then or good to go?

**Comment by d--j** [comment]
all fine here – maybe doc changes would be beneficial, thou.
